version: 2
jobs:
  test:
    docker:
      - image: circleci/node:11.13.0
    environment:
      <<: *COVERAGE_PARAMETERS
    steps:
      - checkout
      - run:
          name: Create coverage report dir
          command: mkdir -p ${COVERAGE_REPORT_DIR}
      - restore_cache:
          keys:
            - v1-yarn-deps-{{ checksum "yarn.lock" }}
            - v1-yarn-deps-
      - run:
          name: Set up yarn tests
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run yarn tests
          command: yarn test
      - persist_to_workspace:
          root: coverage-reports
          paths:
            - lcov.info

  publish-npm:
    docker:
      - image: circleci/node:11.13.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build the library
          command: yarn build
      - run:
          name: Authenticate with npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish --access public
          working_directory: ./draymed_js
      - run:
          name: Create git tag
          command: git tag v$(node -p "require('./package.json').version")
      - run:
          name: Push git tag
          command: git push --tags

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: polaris-foundation
      - publish-npm:
          context: polaris-foundation
          requires:
            - test
          filters:
            branches:
              only:
                - main
